# Configure this Discovery Server
spring:
  application:
    name: proxy-service

server:
  port: 8081   # HTTP (Tomcat) port

  
zuul:
  ignoredServices: '*'
  routes:
    autenticacion:
      path: /api/autenticacion**
      serviceId: autenticacion
      stripPrefix: false
      url: http://autenticacion:8090

    presentVerb:
      path: /api/present/verb/**
      serviceId: presentVerb
      stripPrefix: false
      url: http://present-verb:8091
    
